name: agaami
favicon: null
layout_spectrum: 0.16039
typography_spectrum: 0.7216
title: Agaami LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d4d4d'
    - '#7c7b7c'
    - '#dfdbda'
    - '#f69945'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
