name: agaami
favicon: null
layout_spectrum: 0.2606713706627488
typography_spectrum: 0.2442
title: Agaami LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4d4d'
    - '#ffffff'
    - '#000000'
    - '#aaaaaa'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
