name: agaami
favicon: null
layout_spectrum: 0.2606713706627488
typography_spectrum: 0.36708779726177454
title: Agaami LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7381037906743586
  lightness: 0.3697470168117434
  saturation: 0.38657414354383945
  rhythmicContrast: 0.8265814238693565
purpose: []
